Error processing line 1 of /home/tkadelka/.local/lib/python3.7/site-packages/autorunrecord-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.7/site.py", line 174, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
[WARNING] realpath of PWD=/data/project/rehab_eNKI/eNKI_data/code is /data/project/rehab_eNKI/eNKI_data/code whenever os.getcwd()=/data/project/rehab_eNKI/eNKI_data. From now on will be returning os.getcwd(). Directory symlinks in the paths will be resolved 
[INFO] Downloading 'https://trends-coins-ni.s3.amazonaws.com/nidropbox/8100_anonymized/20171207_233507_Q3ubR.zip?response-content-disposition=attachment%3Bfilename%3Dscan_data360.zip&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2V4PE5I4KOKW2K76%2F20200211%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200211T005351Z&X-Amz-SignedHeaders=host&X-Amz-Expires=604800&X-Amz-Signature=f808da3aa4bae9f52541531664b5d82b2de8acca747cb476ada11dc5ca0e788c' into '/data/project/rehab_eNKI/eNKI_data/' 
[WARNING] Running addurl resulted in stderr output: fatal: update_ref failed for ref 'refs/heads/git-annex': cannot lock ref 'refs/heads/git-annex': Unable to create '/data/project/rehab_eNKI/eNKI_data/.git/refs/heads/git-annex.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git-annex: git [Param "update-ref",Param "refs/heads/git-annex",Param "204b3439c2d6a059c5f6877d325a03c0ce723430"] failed
CallStack (from HasCallStack):
  error, called at ./Git/Command.hs:39:17 in main:Git.Command
 
